mlst_db:
  data/ngono/mlst_database
positions:
  2044,2045,2597
read_dir:
  none
contig_dir:
  /home/ubuntu/upload
previous_runs:
  none
strictness:
  "partial"
update_db:
  true
max_missing_mst:
  5
bigsdb_tokens:
  /home/ubuntu/.bigsdb_tokens
workdir:
  ngpiperesults
samples:
  /home/ubuntu/upload/samples.txt